# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-16 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20190216_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='number',
        ),
    ]
