# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-17 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_remove_medicine_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='num_pill_missed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='num_pill_taken',
            field=models.IntegerField(default=0),
        ),
    ]
