# Generated by Django 2.1.7 on 2019-02-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='busy',
            field=models.BooleanField(default=0),
        ),
    ]
