# Generated by Django 2.1.7 on 2019-02-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_container_busy'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='drug_id',
            field=models.IntegerField(default=-1),
        ),
    ]
