# Generated by Django 2.1.7 on 2019-02-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20190217_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
