# Generated by Django 2.1.7 on 2019-02-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_medicine_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
