# Generated by Django 2.1.7 on 2019-02-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_auto_20190217_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
