# Generated by Django 2.1.7 on 2019-02-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_auto_20190217_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
